project:
  type: website
  output-dir: _site

website:
  title: "projectx"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
    right:
      - icon: twitter
        href: https//twiter.com/james_polls
        aria-label: James twitter
      - icon: github
        href: github.io/jamesstats
        aria-label: Jamesstats Github 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true