project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: britain.qmd
        text: Great Britain 
      - href: philly.qmd
        text: Philadelphia
      - href: prestwozero.qmd
        text: Election Polls 
    right:
      - icon: twitter
        href: https://twitter.com/james_polls
        aria-label: James twitter
      - icon: github
        href: https://github.com/jamesstats/projectx
        aria-label: Jamesstats Github 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true