project:
  type: website
  output-dir: docs

website:
  search: True 
  reader-mode: False  
  back-to-top-navigation: true 
  page-footer: 
    center: "Copyright 2024, Jamesstats"
    right: 
      - icon: home
        href: index.qmd 
      - icon: github
        href: https://github.com/jamesstats/projectx
      - icon: twitter
        href: https://twitter.com/james_polls
  sidebar:
        
     
    - contents:
      - section: "POLLS"
        contents:
          - text: "2024 Nationa Polls"
            href: US2024.qmd 
          - text: "Swing States"
            href: mipawi.qmd
          - text: "Westminister"
            href: britain.qmd  
          - text: "2020 Polls"
            href: prestwozero.qmd
      - section: "MAPS"
        contents: 
          - text: "Philadelphia 08 vs 12"
            href: philly.qmd
          - text: "Las Vegas" 
            href: lasvegas.qmd
      - section: "Massachusetts"
        contents: 
          - text: "Population"
            href: mass.qmd
          - text: "State House"
            href: MAStateHouse.qmd
          - text: "Lawrence"
            href: lawrence.qmd
            
format:
  html:
    theme: cosmo
css: styles.css  
     