project:
  type: website
  output-dir: docs

website:
  search: True 
  reader-mode: False  
  back-to-top-navigation: true 
  page-footer: 
    center: "Copyright 2024, Jamesstats"
    right: 
      - icon: home
        href: index.qmd 
      - icon: github
        href: https://github.com/jamesstats/projectx
      - icon: twitter
        href: https://twitter.com/james_polls
  sidebar:
        
     
    - contents:
      - section: "Polls"
        contents:
          - text: "Swing States 2024"
            href: mipawi.qmd 
          - text: "Westminister"
            href: britain.qmd  
          - text: "2020 Polls"
            href: prestwozero.qmd
      - section: "Maps"
        contents: 
          - text: "Philadelphia 08 vs 12"
            href: philly.qmd
          - text: "Massachusetts"
            href: mass.qmd 
          - text: "Town of Milton"
            href: Milton.qmd
          - text: "Rep.Tlaib"
            href: tlaib.qmd
          - text: "Las Vegas" 
            href: lasvegas.qmd
          - text: "Lawrence"
            href: lawrence.qmd 
           
            
format:
  html:
    theme: cosmo
css: styles.css  
     