project:
  type: website
  output-dir: docs

website:
  search: True 
  reader-mode: False  
  back-to-top-navigation: true 
  page-footer: 
    center: "Copyright 2024, Jamesstats"
    right: 
      - icon: home
        href: index.qmd 
      - icon: github
        href: https://github.com/jamesstats/projectx
      - icon: twitter
        href: https://twitter.com/james_polls
  sidebar:
        
     
    - contents:
      - section: "POLLS"
        contents:
          - text: "2024 National Polls"
            href: US2024.qmd 
          - text: "Westminister Polls"
            href: britain.qmd  
          - text: "2020 National Polls"
            href: prestwozero.qmd
            
format:
  html:
    theme: cosmo
css: styles.css  
     