project:
  type: website
  output-dir: docs

website:
  search: True 
  reader-mode: False  
  back-to-top-navigation: true 
  page-footer: 
    center: "Copyright 2025, Jamesstats"
    right: 
      - icon: home
        href: index.qmd 
      - icon: github
        href: https://github.com/jamesstats/projectx
      - icon: bluesky
        href: https://bsky.app/jamespolls.bsky.social
      - icon: twitter
        href: https://twitter.com/james_polls 
  sidebar:
        
     
    - contents:
      - section: "POLLS"
        contents:
          - text: "U.K NATIONAL POLLS"
            href: uknext.qmd
          - text: "2024 US PRESIDENTIAL POLLS"
            href: US2024.qmd 
          - text: "2024 U.K GENERAL ELECTIONS"
            href: britain.qmd  
          - text: "2020 US PRESIDENTIAL POLLS"
            href: prestwozero.qmd
            
format:
  html:
    theme: cosmo
css: styles.css  
     