---
title: "2020 Presidential Election National Polls"
editor: visual
---

```{r,A_Polls, echo=FALSE, warning=FALSE,message=FALSE, fig.align='center'} 
library(readxl)
library(zoo)
library(dplyr)
library(ggplot2) 
# getting the excel file
Apolls<- read_excel("~/Documents/elections_files/PollsbyRating.xlsx", sheet = 'A_Polls')
# sma
apollssma <- Apolls %>%
  dplyr::arrange(desc(answer)) %>% 
  dplyr::group_by(answer) %>% 
  dplyr::mutate(pct_02da = zoo::rollmean(pct, k = 2, fill = NA),
                pct_03da = zoo::rollmean(pct, k = 3, fill = NA),
                pct_05da = zoo::rollmean(pct, k = 5, fill = NA),
                pct_21da = zoo::rollmean(pct, k = 6, fill = NA)) %>% 
  dplyr::ungroup() 
#chart 
ggplot(apollssma, mapping = aes(x=end_date, y=pct_02da, color=answer))+
  geom_point(alpha=1/20, size=5)+
  geom_hline(yintercept = 50, linetype=2)+ 
  geom_smooth(method = 'loess', formula = 'y~x',span=0.5, se=FALSE, lwd=2)+
  scale_colour_manual(values = c('#0099ff','yellow', '#ff6666')) +
  theme_bw()+
  scale_y_continuous(limits = c(min(0), max(55)), breaks =c(0,10,20,30,40,50,60))+ 
labs(title = '2020 U.S Presidential Election National Polls',subtitle = 'Polls with A rating',
     caption = "source::538.com\ngithub.com/jamesstats/projectx",x="",y="",color="")+
  theme(legend.position = "bottom",plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic', size = 10),
        plot.caption = element_text(face = 'italic',size = 8))  
  
```

```{r,B_Polls, echo=FALSE, warning=FALSE,message=FALSE, fig.align='center'}
library(readxl)
library(zoo)
library(dplyr)
library(ggplot2) 
# getting the excel file
Bpolls<- read_excel("~/Documents/elections_files/PollsbyRating.xlsx", sheet = 'B_Polls')
# sma
bpollssma <- Bpolls %>%
  dplyr::arrange(desc(answer)) %>% 
  dplyr::group_by(answer) %>% 
  dplyr::mutate(pct_02da = zoo::rollmean(pct, k = 2, fill = NA),
                pct_03da = zoo::rollmean(pct, k = 3, fill = NA),
                pct_05da = zoo::rollmean(pct, k = 5, fill = NA),
                pct_21da = zoo::rollmean(pct, k = 6, fill = NA)) %>% 
  dplyr::ungroup() 
ggplot(bpollssma, mapping = aes(x=end_date, y=pct_02da, color=answer))+
  geom_point(alpha=1/20, size=5)+
  geom_hline(yintercept = 50, linetype=2)+
  geom_smooth(method = 'loess', formula = 'y~x',span=0.5, se=FALSE, lwd=2)+
  scale_colour_manual(values = c('#0099ff','yellow', '#ff6666')) +
  theme_bw()+
  scale_y_continuous(limits = c(min(0), max(55)), breaks =c(0,10,20,30,40,50,60))+
labs(title = '2020 U.S Presidential Election National Polls',subtitle = 'Polls with B & B/C rating',
     caption = "source::538.com\ngithub.com/jamesstats/projectx",x="",y="",color="")+
  theme(legend.position = "bottom",plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic', size = 10),
        plot.caption = element_text(face = 'italic',size = 8)) 
```

```{r,C_Polls, echo=FALSE, warning=FALSE,message=FALSE, fig.align='center'}
library(readxl)
library(zoo)
library(dplyr)
library(ggplot2) 
# getting the excel file
Cpolls<- read_excel("~/Documents/elections_files/PollsbyRating.xlsx", sheet = 'C_Polls')
# sma
cpollssma <- Cpolls %>%
  dplyr::arrange(desc(answer)) %>% 
  dplyr::group_by(answer) %>% 
  dplyr::mutate(pct_02da = zoo::rollmean(pct, k = 2, fill = NA),
                pct_03da = zoo::rollmean(pct, k = 3, fill = NA),
                pct_05da = zoo::rollmean(pct, k = 5, fill = NA),
                pct_21da = zoo::rollmean(pct, k = 6, fill = NA)) %>% 
  dplyr::ungroup() 
# chart
ggplot(cpollssma, mapping = aes(x=end_date, y=pct_02da, color=answer))+
  geom_point(alpha=1/20, size=5)+
  geom_hline(yintercept = 50, linetype=2)+
  geom_smooth(method = 'loess', formula = 'y~x',span=0.5, se=FALSE, lwd=2)+
  scale_colour_manual(values = c('#0099ff','yellow', '#ff6666')) +
  theme_bw()+
  scale_y_continuous(limits = c(min(0), max(55)), breaks =c(0,10,20,30,40,50,60))+ 
labs(title = '2020 U.S Presidential Election National Polls',subtitle = 'Polls with C & C/D rating',
     caption = "source::538.com\ngithub.com/jamesstats/projectx",x="",y="",color="")+
  theme(legend.position = "bottom",plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic', size = 10),
        plot.caption = element_text(face = 'italic',size = 8)) 
```

```{r,No_Ratings, echo=FALSE, warning=FALSE,message=FALSE, fig.align='center'} 
library(readxl) 
library(zoo)
library(dplyr)
library(ggplot2) 
# getting the excel file
nonpolls<- read_excel("~/Documents/elections_files/PollsbyRating.xlsx", sheet = 'Non_Polls')
# sma
npollssma <- nonpolls %>%
  dplyr::arrange(desc(answer)) %>% 
  dplyr::group_by(answer) %>% 
  dplyr::mutate(pct_02da = zoo::rollmean(pct, k = 2, fill = NA),
                pct_03da = zoo::rollmean(pct, k = 3, fill = NA),
                pct_05da = zoo::rollmean(pct, k = 5, fill = NA),
                pct_21da = zoo::rollmean(pct, k = 6, fill = NA)) %>% 
  dplyr::ungroup() 
# chart
ggplot(npollssma, mapping = aes(x=end_date, y=pct_02da, color=answer))+
  geom_point(alpha=1/20, size=5)+
  geom_hline(yintercept = 50, linetype=2)+
  geom_smooth(method = 'loess', formula = 'y~x',span=0.5, se=FALSE, lwd=2)+
  scale_colour_manual(values = c('#0099ff', '#ff6666')) +
  theme_bw()+
  scale_y_continuous(limits = c(min(0), max(55)), breaks =c(0,10,20,30,40,50,60))+ 
labs(title = '2020 U.S Presidential Election National Polls',subtitle = 'Polls with no rating',
     caption = "source::538.com\ngithub.com/jamesstats/projectx",x="",y="",color="")+
  theme(legend.position = "bottom",plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic', size = 10),
        plot.caption = element_text(face = 'italic',size = 8)) 
```

